Update bin/reorder-keys
Co-authored-by: ee7 <45465154+ee7@users.noreply.github.com>

diff --git a/bin/reorder-keys b/bin/reorder-keys
--- a/bin/reorder-keys
+++ b/bin/reorder-keys
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 if [ ! -d exercises ] ; then
-    echo "\"exercises\" directory not found, make sure you're running from the repository root" >&2
+    echo "Error: \"exercises\" directory not found, make sure you're running from the repository root" >&2
     exit 1
 fi
 
